spring.application.name=catalogo-vini

# Connessione al database in Docker
spring.datasource.url=jdbc:mysql://localhost:3306/cantina_db?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

# Hibernate: crea le tabelle automaticamente partendo dalle classi Java
spring.jpa.hibernate.ddl-auto=update
# Mostra le query SQL nel terminale (utile per imparare)
spring.jpa.show-sql=true