spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false

# CORRETTO: usa 'mysql-db' che è il nome del servizio nel tuo docker-compose
spring.datasource.url=jdbc:mysql://mysql-db:3306/cantina_db?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

spring.jpa.hibernate.ddl-auto=update

# Abilita gli endpoint dell'Actuator
management.endpoints.web.exposure.include=health,info,prometheus

# Include metriche dettagliate sulle richieste HTTP (fondamentale per tracciare gli errori 500)
management.metrics.web.server.request.autotime.enabled=true