spring.application.name=catalogo-vini

# Connessione al database
spring.datasource.url=jdbc:mysql://localhost:3306/cantina_db?serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root

# Crea tabelle automaticamente partendo dalle classi java
spring.jpa.hibernate.ddl-auto=update
# Risolve i problemi di redirect su GitHub Codespaces
server.forward-headers-strategy=framework